export default {
	executiveMembers: [
		{
			name: "Chinedu Ekeh",
			position: "PRESIDENT",
			imageURL: "assets/img/members/chinedu ekeh.jpg",
		},
		{
			name: "Cyril Ugwuoke",
			position: "VICE PRESIDENT",
			imageURL: "assets/img/members/ugwuoke-cyril.jpg",
		},
		{
			name: "Emeka Aba",
			position: "SECRETARY",
			imageURL: "assets/img/members/emeka-aba.jpg",
		},
		{
			name: "Fredrick Mba",
			position: "ASSISTANT SECRETARY",
			imageURL: "assets/img/executive/default-avatar.png",
		},
		{
			name: "Ibeh Asogwa",
			position: "TREASURER",
			imageURL: "assets/img/executive/default-avatar.png",
		},
		{
			name: "Levi Onoja",
			position: "FINANCIAL SECRETARY",
			imageURL: "assets/img/executive/default-avatar.png",
		},
		{
			name: "James Urama",
			position: "PUBLIC RELATION OFFICER",
			imageURL: "assets/img/members/james-urama.jpg",
		},
		{
			name: "Ignatius Idoko",
			position: "CHIEF PROVOST",
			imageURL: "assets/img/executive/default-avatar.png",
		},
		{
			name: "Okechukwu Eze",
			position: "ASSISTANT PROVOST 1",
			imageURL: "assets/img/members/eze-godwin.jpg",
		},
		{
			name: "Paschal Elengwu",
			position: "ASSISTANT PROVOST 2",
			imageURL: "assets/img/members/paschal-godswil.jpg",
		},
	],

	boardOfTrustees: [
		{
			name: "Eugene Ngwu",
			position: "CHAIRMAN",
			imageURL: "assets/img/members/ngwu-eugene-ogbonnaya.jpg",
		},
		{
			name: "Fredrick Mba",
			position: "MEMBER",
			imageURL: "assets/img/executive/default-avatar.png",
		},
		{
			name: "Ibeh Asogwa",
			position: "MEMBER",
			imageURL: "assets/img/executive/default-avatar.png",
		},
		{
			name: "Levi Onoja",
			position: "MEMBER",
			imageURL: "assets/img/executive/default-avatar.png",
		},
		{
			name: "Ifeanyi Ujah",
			position: "MEMBER",
			imageURL: "assets/img/executive/default-avatar.png",
		},
		{
			name: "Cyril Ugwuoke",
			position: "MEMBER",
			imageURL: "assets/img/members/ugwuoke-cyril.jpg",
		},
	],
	members: [
		{
			name: "Chinedu Ekeh",
			position: "MEMBER",
			imageURL: "assets/img/members/chinedu ekeh.jpg",
			phone: "",
			email: "",
			bio: "Chinedu Ekeh holds a B. Sc., M. Sc., PMP, and MBA, and is a highly resourceful, creative, and strategic leader with exceptional competence in leveraging business intelligence and often-overlooked intangible attributes to drive extraordinary positive outcomes. He is a Consultant at BOM Consulting Ltd. Outside his professional endeavors, Chinedu enjoys reading, networking, and watching football.",
		},
		{
			name: "Sir Emeka Aba (KSM)",
			position: "MEMBER",
			imageURL: "assets/img/members/emeka-aba.jpg",
			phone: "+2348037046161, +2348153116343",
			email: "emtofurnishing@yahoo.com",
			bio: "Sir Emeka Aba (KSM) is the founder of Emto Conglomerate, a leader in interior design, construction, real estate, and investment. Since its establishment, Emto Conglomerate has been dedicated to providing innovative solutions and high-quality services tailored to meet the unique needs of its clients. Headquartered at Emto Plaza, Plot C9, 4th Avenue, Gwarinpa Estate, the company also operates a branch office at Suite F9, Say Plaza, A.E. Ekukinam Street, Utako, Abuja, ensuring seamless operations and client accessibility.",
		},
		{
			name: "Mr. Eze Godwin Okechukwu",
			position: "MEMBER",
			imageURL: "assets/img/members/eze-godwin.jpg",
			phone: "",
			email: "",
			bio: "Mr. Eze Godwin Okechukwu is the CEO/MD of Great Okeyson Investment Concept Ltd, a prominent importer and exporter of England materials, electrical and electronic goods, building materials, and general contracting services. Located at Shop M2, Gudu Market, FCT Abuja, Great Okeyson Investment Concept Ltd is known for providing high-quality products and services that cater to a wide range of client needs.",
		},
		{
			name: "Ibeh Asogwa",
			position: "MEMBER",
			imageURL: "assets/img/executive/default-avatar.png",
		},
		{
			name: "Fred Mba",
			position: "MEMBER",
			imageURL: "assets/img/executive/default-avatar.png",
		},
		{
			name: "Levi Onoja",
			position: "MEMBER",
			imageURL: "assets/img/executive/default-avatar.png",
		},
		{
			name: "Mr. James Urama",
			position: "MEMBER",
			imageURL: "assets/img/members/james-urama.jpg",
			phone: "08035901343",
			email: "",
			bio: "Mr. James Urama is the CEO/MD of Winners Divine Electrical Ltd. and Winford Solar, specializing in electrical and solar materials. With expertise as a solar solutions expert and in electrical fittings, the company provides top-quality products and services. Located at Shop A15, NAOWA Shopping Complex, Mararaba via Nyanya, FCT Abuja, Winners Divine Electrical Ltd. and Winford Solar are trusted names in the industry for reliable and innovative energy solutions.",
		},

		{
			name: "Ignatius Idoko",
			position: "MEMBER",
			imageURL: "assets/img/executive/default-avatar.png",
		},
		{
			name: "Okey Eze",
			position: "MEMBER",
			imageURL: "assets/img/executive/default-avatar.png",
		},
		{
			name: "Paschal Elengwu",
			position: "MEMBER",
			imageURL: "assets/img/members/paschal-godswil.jpg",
			phone: "08034504156, 08168700403",
			email: "",
			bio: "Paschal Elengwu is the Executive Director at Global Services Ltd, a company specializing in wood and building materials. As general merchants, they offer a wide range of high-quality products to meet the needs of their clients. The company is headquartered at Block L5, Shop 124, International Timber Shed, Dei-Dei, Abuja F.C.T. Their motto, 'Tested and Trusted,' reflects their commitment to excellence and reliability in the industry.",
		},

		{
			name: "Ifeanyi Ujah",
			position: "MEMBER",
			imageURL: "assets/img/executive/default-avatar.png",
		},
		{
			name: "Ngwu Eugene Ogbonnaya",
			position: "MEMBER",
			imageURL: "assets/img/members/ngwu-eugene-ogbonnaya.jpg",
			phone: "08039471405, 08054222543",
			email: "",
			bio: "Ngwu Eugene Ogbonnaya is a seasoned business entrepreneur, professional interior designer, and decorator. He is also the chairman of the Board of Trustees of the Noble Club. With a passion for design and business, he has made significant contributions to the fields of interior design and entrepreneurship.",
		},
		{
			name: "Chief Bonaventure Ezea",
			position: "MEMBER",
			imageURL: "assets/img/members/bonaventure-ezea.jpg",
			phone: "08037862377, 08059889614",
			email: "ezeabonaventure@gmail.com",
			bio: "Chief Bonaventure Ezea is the MD/CEO of BONAVEE INVEST. CO NIG. LTD., a leading supplier of wines, hot drinks, and beverages. The company also specializes in event management and general contracting. Located at DGF 1 K-City Plaza, Plot 528 Aminu Kano Crescent, Wuse II, Abuja, BONAVEE INVEST. CO NIG. LTD. is dedicated to making every occasion a success, prioritizing client satisfaction and excellence in service.",
		},
		{
			name: "Kenneth Odo",
			position: "MEMBER",
			imageURL: "assets/img/executive/default-avatar.png",
		},
		{
			name: "Chief David Ugwu",
			position: "MEMBER",
			imageURL: "assets/img/members/david-ugwu.jpg",
			phone: "08033273093, 08155520990, 07067741177",
			email: "",
			bio: "Chief David Ugwu is the CEO/MD of Kings International Boutique LTD, a leading provider of quality clothing and accessories. The boutique specializes in jeans, chinos trousers, Turkey suits, China suits, shirts, pocket shirts, chieftaincy wears, caps, children's wear, school sandals, and more. Located at Block 14, Shop No. 148, Wuse Modern Market, FCT Abuja, Kings International Boutique LTD is dedicated to offering stylish and affordable apparel for all occasions.",
		},
		{
			name: "Comrade Onuh Camillus",
			position: "MEMBER",
			imageURL: "assets/img/members/onuh-camillus.jpg",
			phone: "+2348033856813",
			email: "camicamp8@gmail.com",
			bio: "Comrade Onuh Camillus is the CEO of Cami Camp Investment Ltd, a company incorporated with the Nigerian Corporate Affairs Commission since 2006. The company specializes in household appliances, including electronics, furniture, generators, and solar and inverter energy systems. With a commitment to the labour market, the company has employed about fifteen workers, contributing to economic growth. Headquartered at The Ruby Center Plaza, Aminu Kano Way, Wuse 2, Abuja, Cami Camp Investment Ltd also operates other outlets across Abuja and its environs and provides delivery services to other states in Nigeria. The company's primary goal is building lasting relationships and ensuring customer satisfaction. Social media: Facebook - Cami Camp Electronics Showroom, Instagram - @CamiCamp6.",
		},
		{
			name: "Comrade Charles Onuh",
			position: "MEMBER",
			imageURL: "assets/img/members/charles-onuh.jpg",
			phone: "08060651212",
			email: "",
			bio: "Comrade Charles Onuh is the CEO/MD of Charlon Integrated Concept & Synergy Ltd., a reputable dealer and supplier of high-quality building materials. The company specializes in products such as iron rods, U channels, H channels, square pipes, and angle irons. Located at Shop No. D4-146, Dei-Dei International Building Materials Market, FCT Abuja, Charlon Integrated Concept & Synergy Ltd. is committed to providing reliable and durable building solutions to its clients.",
		},
		{
			name: "Valentine Nwodo",
			position: "MEMBER",
			imageURL: "assets/img/executive/default-avatar.png",
		},
		{
			name: "Micheal Odo",
			position: "MEMBER",
			imageURL: "assets/img/executive/default-avatar.png",
		},
		{
			name: "Oliver Eze",
			position: "MEMBER",
			imageURL: "assets/img/executive/default-avatar.png",
		},
		{
			name: "Celestine Ogbu",
			position: "MEMBER",
			imageURL: "assets/img/executive/default-avatar.png",
		},
		{
			name: "Chika Donatus Ugwuanyi",
			position: "MEMBER",
			imageURL: "assets/img/members/chika-donatus.jpg",
			phone: "08055104849, 08039737835, 08026852425, 08036861868",
			email: "jestyoil.gasltd@gmail.com",
			bio: "Chika Donatus Ugwuanyi is the MD/CEO of JESTY OIL & GAS LTD, a company specializing in the mining, exploration, and distribution of oil and gas reserves. With office locations at No. 9 PPMC/NNPCL Depot, off Kaduna/Abuja Expressway, Maje, Suleja, Abuja, and a branch at Suite 208, 2nd Floor, N.E.C., opposite Millennium Tower, behind the National Mosque, Central Business District, Abuja, JESTY OIL & GAS LTD is committed to providing reliable energy solutions. The company also offers door-to-door deliveries, ensuring constant energy supply to its clients. Your satisfaction and energy needs are their top priorities.",
		},
		{
			name: "Kenneth Okenyi",
			position: "MEMBER",
			imageURL: "assets/img/executive/default-avatar.png",
		},
		{
			name: "Ifeanyi Eze Kenneth",
			position: "MEMBER",
			imageURL: "assets/img/executive/default-avatar.png",
		},
		{
			name: "Mr. Ugwu Johnkingsley",
			position: "MEMBER",
			imageURL: "assets/img/members/ugwu-kingsley.jpg",
			phone: "",
			email: "",
			bio: "Mr. Ugwu Johnkingsley is the CEO/MD of Okins Global Concept Ent Ltd, a company specializing in motor spare parts, batteries, and accessories for all models of Volkswagen and Mercedes vehicles. The company operates from Shop A3 & A31, E. Ekeson Plaza, beside Utako Model Market, FCT Abuja, and is known for providing high-quality, reliable automotive products and services.",
		},
		{
			name: "Anselm Onugwu",
			position: "MEMBER",
			imageURL: "assets/img/members/anselem-onugwu.jpg",
			phone: "08035968925",
			email: "worldwide785@gmail.com",
			bio: "Mr. Anselem Onugwu is the CEO of Anseson Worldwide Nig Ltd, a distributor for Longxiang Aluminium Company Ltd, and a contractor specializing in all kinds of building construction. Based at Block 7, No. 14 Habitat Plaza, Aluminium Village, Kaduna Road, Abuja, he is a dedicated professional with extensive experience in the aluminium and construction industries.",
		},
		{
			name: "Martins Idokoja",
			position: "MEMBER",
			imageURL: "assets/img/executive/default-avatar.png",
		},
		{
			name: "Mr. Ugwuoke Cyril Chukwuemeka",
			position: "MEMBER",
			imageURL: "assets/img/members/ugwuoke-cyril.jpg",
			phone: "08065447557, 08175447557",
			email: "",
			bio: "Mr. Ugwuoke Cyril Chukwuemeka is the CEO of Cyco Integrated Concept Ltd, a company specializing in distributing foreign beverages directly to customers' doorsteps. He is also the CEO of MC Bolac Investment Ltd, with a mission to become a leading service provider in solar energy, construction, and engineering services. The company is driven by core values of commitment to excellence, integrity, and customer satisfaction, aiming to provide high-quality services while maintaining upright business ethics. Cyco Integrated Concept Ltd operates from Blk D118, Wuse Modern Market, Wuse, Abuja.",
		},
		{
			name: "Mr. Omeke Kenneth Okwudili",
			position: "MEMBER",
			imageURL: "assets/img/members/omeke-kenneth.jpg",
			phone: "08036727833, 0909038904427",
			email: "",
			bio: "Mr. Omeke Kenneth Okwudili is the CEO/MD of Kenomek Int Nig Ltd, a leading dealer in all kinds of welding materials, including iron pipes, iron rods, and general goods. The company operates from No E2 & E3 Maraba Iron Dealers Ass Market, Sharp Corner, behind Chess Pub, along Assembly of God Road. Kenomek Int Nig Ltd is known for providing high-quality welding materials and services to its customers.",
		},
		{
			name: "Ali Amobi Maurice",
			position: "MEMBER",
			imageURL: "assets/img/members/amobi-maurice.jpg",
			phone: "08063511800",
			email: "",
			bio: "Ali Amobi Maurice is a Superintendent of Customs with expertise in International Financial Reporting Standards (IFRSs) and Non-Intrusive Inspection Technology (NIIT). He is based at Office 3, Abidjan Street, Wuse Zone 3, Abuja, and brings extensive knowledge and experience in customs operations and financial reporting.",
		},
		{
			name: "Onyebuchi Mamah",
			position: "MEMBER",
			imageURL: "assets/img/executive/default-avatar.png",
		},
		{
			name: "Oliver David Onyeke",
			position: "MEMBER",
			imageURL: "assets/img/executive/default-avatar.png",
		},
	],
	resources: [
		{
			icon: "bx bxs-file-doc",
			title: "Our Constitution",
			description:
				"This Document contains our revised constitution dated 25 August 2022",
			downloadlink: "assets/resources/revised-constitution.pdf",
		},
	],
	gallery: [
		{ url: "assets/img/gallery/gallery (1).jpg" },
		{ url: "assets/img/gallery/gallery (2).jpg" },
		{ url: "assets/img/gallery/gallery (3).jpg" },
		{ url: "assets/img/gallery/gallery (4).jpg" },
		{ url: "assets/img/gallery/gallery (5).jpg" },
		{ url: "assets/img/gallery/gallery (6).jpg" },
		{ url: "assets/img/gallery/gallery (7).jpg" },
		{ url: "assets/img/gallery/gallery (8).jpg" },
		{ url: "assets/img/gallery/gallery (9).jpg" },
		{ url: "assets/img/gallery/gallery (10).jpg" },
		{ url: "assets/img/gallery/gallery (11).jpg" },
		{ url: "assets/img/gallery/gallery (12).jpg" },
		{ url: "assets/img/gallery/gallery (13).jpg" },
		{ url: "assets/img/gallery/gallery (14).jpg" },
		{ url: "assets/img/gallery/gallery (15).jpg" },
		{ url: "assets/img/gallery/gallery (16).jpg" },
		{ url: "assets/img/gallery/gallery (17).jpg" },
		{ url: "assets/img/gallery/gallery (18).jpg" },
		{ url: "assets/img/gallery/gallery (19).jpg" },
		{ url: "assets/img/portfolio/image_one.jpg" },
		{ url: "assets/img/gallery/gallery-1.jpg" },
		{ url: "assets/img/gallery/gallery-2.jpg" },
		{ url: "assets/img/gallery/gallery-3.jpg" },
		{ url: "assets/img/gallery/gallery-5.jpg" },
		{ url: "assets/img/gallery/gallery-6.jpg" },
	],
};
