export default {
	executiveMembers: [
		{
			name: "Chinedu Ekeh",
			position: "PRESIDENT",
			imageURL: "assets/img/members/chinedu ekeh.jpg",
		},
		{
			name: "Cyril Ugwuoke",
			position: "VICE PRESIDENT",
			imageURL: "assets/img/members/ugwuoke-cyril.jpg",
		},
		{
			name: "Emeka Aba",
			position: "SECRETARY",
			imageURL: "assets/img/members/emeka-aba.jpg",
		},
		{
			name: "Fredrick Mba",
			position: "ASSISTANT SECRETARY",
			imageURL: "assets/img/members/mba-frederick.jpg",
		},
		{
			name: "Ibeh Asogwa",
			position: "TREASURER",
			imageURL: "assets/img/executive/default-avatar.png",
		},
		{
			name: "Levi Onoja",
			position: "FINANCIAL SECRETARY",
			imageURL: "assets/img/members/onoja-levi.jpg",
		},
		{
			name: "James Urama",
			position: "PUBLIC RELATION OFFICER",
			imageURL: "assets/img/members/james-urama.jpg",
		},
		{
			name: "Ignatius Idoko",
			position: "CHIEF PROVOST",
			imageURL: "assets/img/members/ignatius-ifeanyi-idoko.jpg",
		},
		{
			name: "Okechukwu Eze",
			position: "ASSISTANT PROVOST 1",
			imageURL: "assets/img/members/eze-godwin.jpg",
		},
		{
			name: "Paschal Elengwu",
			position: "ASSISTANT PROVOST 2",
			imageURL: "assets/img/members/paschal-godswil.jpg",
		},
	],

	boardOfTrustees: [
		{
			name: "Eugene Ngwu",
			position: "CHAIRMAN",
			imageURL: "assets/img/members/ngwu-eugene-ogbonnaya.jpg",
		},
		{
			name: "Fredrick Mba",
			position: "MEMBER",
			imageURL: "assets/img/members/mba-frederick.jpg",
		},
		{
			name: "Ibeh Asogwa",
			position: "MEMBER",
			imageURL: "assets/img/executive/default-avatar.png",
		},
		{
			name: "Levi Onoja",
			position: "MEMBER",
			imageURL: "assets/img/members/onoja-levi.jpg",
		},
		{
			name: "Ifeanyi Ujah",
			position: "MEMBER",
			imageURL: "assets/img/members/ifeanyi-ujah.jpg",
		},
		{
			name: "Cyril Ugwuoke",
			position: "MEMBER",
			imageURL: "assets/img/members/ugwuoke-cyril.jpg",
		},
	],
	members: [
		{
			name: "Chinedu Ekeh",
			position: "MEMBER",
			imageURL: "assets/img/members/chinedu ekeh.jpg",
			phone: "",
			email: "",
			bio: "Chinedu Ekeh holds a B. Sc., M. Sc., PMP, and MBA, and is a highly resourceful, creative, and strategic leader with exceptional competence in leveraging business intelligence and often-overlooked intangible attributes to drive extraordinary positive outcomes. He is a Consultant at BOM Consulting Ltd. Outside his professional endeavors, Chinedu enjoys reading, networking, and watching football.",
		},
		{
			name: "Mr. Cyril Chukwuemeka Ugwuoke",
			position: "MEMBER",
			imageURL: "assets/img/members/ugwuoke-cyril.jpg",
			phone: "08065447557, 08175447557",
			email: "",
			bio: "Mr. Cyril Chukwuemeka Ugwuoke is the CEO of Cyco Integrated Concept Ltd, a company specializing in distributing foreign beverages directly to customers' doorsteps. He is also the CEO of MC Bolac Investment Ltd, with a mission to become a leading service provider in solar energy, construction, and engineering services. The company is driven by core values of commitment to excellence, integrity, and customer satisfaction, aiming to provide high-quality services while maintaining upright business ethics. Cyco Integrated Concept Ltd operates from Blk D118, Wuse Modern Market, Wuse, Abuja.",
		},

		{
			name: "Sir Emeka Aba (KSM)",
			position: "MEMBER",
			imageURL: "assets/img/members/emeka-aba.jpg",
			phone: "+2348037046161, +2348153116343",
			email: "emtofurnishing@yahoo.com",
			bio: "Sir Emeka Aba (KSM) is the founder of Emto Conglomerate, a leader in interior design, construction, real estate, and investment. Since its establishment, Emto Conglomerate has been dedicated to providing innovative solutions and high-quality services tailored to meet the unique needs of its clients. Headquartered at Emto Plaza, Plot C9, 4th Avenue, Gwarinpa Estate, the company also operates a branch office at Suite F9, Say Plaza, A.E. Ekukinam Street, Utako, Abuja, ensuring seamless operations and client accessibility.",
		},
		{
			name: "Mr. Godwin Okechukwu Eze ",
			position: "MEMBER",
			imageURL: "assets/img/members/eze-godwin.jpg",
			phone: "",
			email: "",
			bio: "Mr. Godwin Okechukwu Eze is the CEO/MD of Great Okeyson Investment Concept Ltd, a prominent importer and exporter of England materials, electrical and electronic goods, building materials, and general contracting services. Located at Shop M2, Gudu Market, FCT Abuja, Great Okeyson Investment Concept Ltd is known for providing high-quality products and services that cater to a wide range of client needs.",
		},
		{
			name: "Ibeh Asogwa",
			position: "MEMBER",
			imageURL: "assets/img/executive/default-avatar.png",
		},
		{
			name: "Mba Frederick O",
			position: "MEMBER",
			imageURL: "assets/img/members/mba-frederick.jpg",
			phone: "08033334345, 08036238644",
			email: "mbamain@yahoo.com",
			bio: "Mba Frederick O is the CEO of Fredo Associates Intl Ltd, a trusted name in the supply of stationeries, computer accessories, and office equipment. With a strong commitment to quality and reliability, the company serves businesses and individuals with top-grade products. Fredo Associates Intl Ltd operates from Warehouse 121, Utako Market, FCT, Abuja, and Block A8, Shop 4, Wuse Modern Market, ensuring easy access to premium office solutions. With a reputation built on excellence, the company remains a go-to destination for office essentials.",
		},
		{
			name: "Comrade Onoja Levi",
			position: "MEMBER",
			imageURL: "assets/img/members/onoja-levi.jpg",
			phone: "08050552626",
			email: "",
			bio: "Comrade Onoja Levi is a skilled and prudent manager, widely recognized as an enigma in interior and exterior decoration. As the CEO of Onowax Noble Limited, he has built a reputation for excellence in contracting and general merchandise, delivering high-quality solutions tailored to client needs. A passionate reader of news and history, Comrade Onoja Levi combines his business acumen with a deep understanding of design and construction to create exceptional living and working spaces.",
		},

		{
			name: "Mr. James Urama",
			position: "MEMBER",
			imageURL: "assets/img/members/james-urama.jpg",
			phone: "08035901343",
			email: "",
			bio: "Mr. James Urama is the CEO/MD of Winners Divine Electrical Ltd. and Winford Solar, specializing in electrical and solar materials. With expertise as a solar solutions expert and in electrical fittings, the company provides top-quality products and services. Located at Shop A15, NAOWA Shopping Complex, Mararaba via Nyanya, FCT Abuja, Winners Divine Electrical Ltd. and Winford Solar are trusted names in the industry for reliable and innovative energy solutions.",
		},

		{
			name: "Ignatius Idoko",
			position: "MEMBER",
			imageURL: "assets/img/members/ignatius-ifeanyi-idoko.jpg",
			phone: "08033032264",
			email: "igidoko@gmail.com",
			bio: "Comrade Ignatius Ifeanyi Idoko is the CEO of Ignel Investments Ltd, a reputable dealer in high-quality traveling boxes, conference bags, and office bags. Renowned for offering durable and stylish products, Ignel Investments Ltd caters to both individual and corporate needs with a focus on quality and customer satisfaction. The company operates from its head office at Block B21, Shop 5, Wuse Modern Market, Abuja, Nigeria, ensuring convenient access and exceptional service.",
		},

		{
			name: "Paschal Elengwu",
			position: "MEMBER",
			imageURL: "assets/img/members/paschal-godswil.jpg",
			phone: "08034504156, 08168700403",
			email: "",
			bio: "Paschal Elengwu is the Executive Director at Global Services Ltd, a company specializing in wood and building materials. As general merchants, they offer a wide range of high-quality products to meet the needs of their clients. The company is headquartered at Block L5, Shop 124, International Timber Shed, Dei-Dei, Abuja F.C.T. Their motto, 'Tested and Trusted,' reflects their commitment to excellence and reliability in the industry.",
		},
		{
			name: "Obetta Peter Chijioke",
			position: "MEMBER",
			imageURL: "assets/img/members/obetta-cjpeters.jpg",
			phone: "",
			email: "",
			bio: "Obetta Peter Chijioke, popularly known as Obetta CJPeters, is a renowned health-tech entrepreneur, certified pharmacist, and healthcare practitioner. Born on August 24, 1982, he is the founder and CEO of Health Hub Pharmaceutical Ltd, a leading player in the pharmaceutical and health-tech industry. With a wealth of experience, he also serves on the boards of several companies, contributing his expertise to the advancement of healthcare and business innovation in Nigeria.",
		},

		{
			name: "Ifeanyi Ujah",
			position: "MEMBER",
			imageURL: "assets/img/members/ifeanyi-ujah.jpg",
			phone: "08033298129",
			email: "Sosocurtains@gmail.com",
			bio: "Ifeanyi Ujah is the CEO/MD of SOSO Furnishing Ltd., a distinguished brand in the interior décor and home furnishing industry. Specializing in premium-quality curtains, blinds, and accessories, the company is known for delivering elegant and functional interior solutions tailored to clients' unique tastes. The company operates from its head office, offering bespoke furnishing services and top-tier products that redefine comfort and style in homes and commercial spaces across Nigeria."
		},
		{
			name: "Ngwu Eugene Ogbonnaya",
			position: "MEMBER",
			imageURL: "assets/img/members/ngwu-eugene-ogbonnaya.jpg",
			phone: "08039471405, 08054222543",
			email: "",
			bio: "Ngwu Eugene Ogbonnaya is a seasoned business entrepreneur, professional interior designer, and decorator. He is also the chairman of the Board of Trustees of the Noble Club. With a passion for design and business, he has made significant contributions to the fields of interior design and entrepreneurship.",
		},
		{
			name: "Chief Bonaventure Ezea",
			position: "MEMBER",
			imageURL: "assets/img/members/bonaventure-ezea.jpg",
			phone: "08037862377, 08059889614",
			email: "ezeabonaventure@gmail.com",
			bio: "Chief Bonaventure Ezea is the MD/CEO of BONAVEE INVEST. CO NIG. LTD., a leading supplier of wines, hot drinks, and beverages. The company also specializes in event management and general contracting. Located at DGF 1 K-City Plaza, Plot 528 Aminu Kano Crescent, Wuse II, Abuja, BONAVEE INVEST. CO NIG. LTD. is dedicated to making every occasion a success, prioritizing client satisfaction and excellence in service.",
		},
		{
			name: "Mr. Kenneth Egwuatuchi Odo",
			position: "MEMBER",
			imageURL: "assets/img/members/kenneth-odo.jpg",
			phone: "08033938587",
			email: "kendoglobal@gmail.com, odokenneth17@gmail.com",
			bio: "Mr. Kenneth Egwuatuchi Odo is the CEO of Kendo Global Ventures Ltd, a leading importer and distributor of premium-quality bags, including luggage, conference bags, backpacks, and more. With a strong commitment to excellence, Kendo Global Ventures Ltd provides a diverse range of stylish and durable bags tailored to meet various needs. The company operates from its head office at D2 LS 04, Utako Mall, FCT, Abuja, ensuring accessibility and top-notch customer service.",
		},

		{
			name: "Chief David Ugwu",
			position: "MEMBER",
			imageURL: "assets/img/members/david-ugwu.jpg",
			phone: "08033273093, 08155520990, 07067741177",
			email: "",
			bio: "Chief David Ugwu is the CEO/MD of Kings International Boutique LTD, a leading provider of quality clothing and accessories. The boutique specializes in jeans, chinos trousers, Turkey suits, China suits, shirts, pocket shirts, chieftaincy wears, caps, children's wear, school sandals, and more. Located at Block 14, Shop No. 148, Wuse Modern Market, FCT Abuja, Kings International Boutique LTD is dedicated to offering stylish and affordable apparel for all occasions.",
		},
		{
			name: "Comrade Camillus Onuh",
			position: "MEMBER",
			imageURL: "assets/img/members/onuh-camillus.jpg",
			phone: "+2348033856813",
			email: "camicamp8@gmail.com",
			bio: "Comrade Onuh Camillus is the CEO of Cami Camp Investment Ltd, a company incorporated with the Nigerian Corporate Affairs Commission since 2006. The company specializes in household appliances, including electronics, furniture, generators, and solar and inverter energy systems. With a commitment to the labour market, the company has employed about fifteen workers, contributing to economic growth. Headquartered at The Ruby Center Plaza, Aminu Kano Way, Wuse 2, Abuja, Cami Camp Investment Ltd also operates other outlets across Abuja and its environs and provides delivery services to other states in Nigeria. The company's primary goal is building lasting relationships and ensuring customer satisfaction. Social media: Facebook - Cami Camp Electronics Showroom, Instagram - @CamiCamp6.",
		},
		{
			name: "Comrade Charles Onuh",
			position: "MEMBER",
			imageURL: "assets/img/members/charles-onuh.jpg",
			phone: "08060651212",
			email: "",
			bio: "Comrade Charles Onuh is the CEO/MD of Charlon Integrated Concept & Synergy Ltd., a reputable dealer and supplier of high-quality building materials. The company specializes in products such as iron rods, U channels, H channels, square pipes, and angle irons. Located at Shop No. D4-146, Dei-Dei International Building Materials Market, FCT Abuja, Charlon Integrated Concept & Synergy Ltd. is committed to providing reliable and durable building solutions to its clients.",
		},
		{
			name: "Valentine Nwodo",
			position: "MEMBER",
			imageURL: "assets/img/members/valentine-nwodo1.jpg",
			phone: "08055144020",
			email:"valolivet@yahoo.com",
			bio: "Comrade Valentine Nwodo is the CEO/MD of VTino Industry Ltd Building Material Hub, a trusted name in the supply of high-quality construction materials. The company specializes in quarry products, including dust, stone base, chippings, and also operates a block industry. In addition to his business ventures, he is the founder of Valintino Empowerment Foundation, through which he has empowered and supported numerous individuals across Enugu State. With a strong presence in both real estate and philanthropy, Comrade Valentine Nwodo continues to make a lasting impact in his community. For more information, visit [www.valintino-ef.com](http://www.valintino-ef.com).",

		},
		{
			name: "Michael Odo",
			position: "MEMBER",
			imageURL: "assets/img/members/michael-odo.jpg",
			phone: "08035972983",
			email: "",
			bio: "Michael Odo is the founder and CEO of 5:3 Agro, Vet and Farms, a leading agricultural enterprise located along Keffi Expressway, Gora, Nasarawa State. The farm specializes in livestock farming, including poultry, piggery, fishery, and goats, as well as crop and vegetable farming. With a commitment to sustainable agriculture and high-quality production, 5:3 Agro, Vet and Farms provides nutritious food products and reliable livestock solutions to meet the growing demands of the agricultural sector.",
		},

		{
			name: "Oliver Eze",
			position: "MEMBER",
			imageURL: "assets/img/executive/default-avatar.png",
		},
		{
			name: "Celestine Ogbu",
			position: "MEMBER",
			imageURL: "assets/img/members/celestine-ogbu.jpg",
			phone: "08033143562",
			email: "",
			bio:"Hon. Celestine Ogbu is a grassroot politician, philanthropist and the CEO of CELON INVESTMENT CO LTD(CICL). He is an Eago Distributor; Jacuzzi, Bathroom Accessories, Plumbing tiles, Iron Rod and Electricals dealer. Celon Investment Co. Ltd operates from its head office at Nandu Plaza, Wuse Zone 5, opposite Anbeez Plaza, beside Old CAC, with shops 1, 2, 3, and 4 serving as key retail points. With several branch offices across the region, CICL is committed to delivering premium products and exceptional service to its growing clientele.",
		},
		{
			name: "Chika Donatus Ugwuanyi",
			position: "MEMBER",
			imageURL: "assets/img/members/chika-donatus.jpg",
			phone: "08055104849, 08039737835, 08026852425, 08036861868",
			email: "jestyoil.gasltd@gmail.com",
			bio: "Chika Donatus Ugwuanyi is the MD/CEO of JESTY OIL & GAS LTD, a company specializing in the mining, exploration, and distribution of oil and gas reserves. With office locations at No. 9 PPMC/NNPCL Depot, off Kaduna/Abuja Expressway, Maje, Suleja, Abuja, and a branch at Suite 208, 2nd Floor, N.E.C., opposite Millennium Tower, behind the National Mosque, Central Business District, Abuja, JESTY OIL & GAS LTD is committed to providing reliable energy solutions. The company also offers door-to-door deliveries, ensuring constant energy supply to its clients. Your satisfaction and energy needs are their top priorities.",
		},
		{
			name: "Kenneth Okenyi",
			position: "MEMBER",
			imageURL: "assets/img/members/okenyi-kenneth.jpg",
			phone: "08131670973",
			email: "",
			bio:"Comrade Okenyi Kenneth Egwuatu is the CEO/MD of Kenndo Block Industry Nig. Ltd. Renowned for delivering high-quality concrete blocks and construction solutions, the company has built a solid reputation for reliability and excellence in service delivery. Kenndo Block Industry Nig. Ltd operates from its head office located behind Pascal Academy, UND Street, Kabayi Area office."
		},
		{
			name: "Mr.Kenneth Ifeanyi Ezeh",
			position: "MEMBER",
			imageURL: "assets/img/members/ezeh-kenneth.jpg",
			phone: "",
			email: "",
			bio: "Mr. Ezeh Kenneth Ifeanyi is the CEO/MD of Anyikenz Nigeria Limited, a trusted name in the distribution, importation, and retail of high-quality shoe materials. His company specializes in sole, maco, gum, nora, superglue, and general goods, serving a wide range of customers in the footwear and manufacturing industry. Anyikenz Nigeria Limited is strategically located at Shop 727/728, Nyanya Old Motor Park, Abuja, FCT, ensuring accessibility and convenience for clients seeking premium materials and reliable service.",
		},
		{
			name: "Mr. Johnkingsley Ugwu",
			position: "MEMBER",
			imageURL: "assets/img/members/ugwu-kingsley.jpg",
			phone: "",
			email: "",
			bio: "Mr. Ugwu Johnkingsley is the CEO/MD of Okins Global Concept Ent Ltd, a company specializing in motor spare parts, batteries, and accessories for all models of Volkswagen and Mercedes vehicles. The company operates from Shop A3 & A31, E. Ekeson Plaza, beside Utako Model Market, FCT Abuja, and is known for providing high-quality, reliable automotive products and services.",
		},
		{
			name: "Anselm Onugwu",
			position: "MEMBER",
			imageURL: "assets/img/members/anselem-onugwu.jpg",
			phone: "08035968925",
			email: "worldwide785@gmail.com",
			bio: "Mr. Anselem Onugwu is the CEO of Anseson Worldwide Nig Ltd, a distributor for Longxiang Aluminium Company Ltd, and a contractor specializing in all kinds of building construction. Based at Block 7, No. 14 Habitat Plaza, Aluminium Village, Kaduna Road, Abuja, he is a dedicated professional with extensive experience in the aluminium and construction industries.",
		},
		{
			name: "Comrade Martins Idokoja",
			position: "MEMBER",
			imageURL: "assets/img/members/martins-idokoja.jpg",
			phone: "08036099725",
			email: "",
			bio: "Comrade Martins Idokoja is the MD/CEO of De Auto Martins Integrated Nig Ltd, a trusted name in the automotive industry. The company specializes in the sales of all brands of new tyres, batteries, and alloy wheels, ensuring customers receive high-quality and durable products. De Auto Martins Integrated Nig Ltd also offers professional wheel balancing and both front and back alignment services, delivering precision and safety to vehicle owners.",
		},

		{
			name: "Mr. Kenneth Okwudili Omeke",
			position: "MEMBER",
			imageURL: "assets/img/members/omeke-kenneth.jpg",
			phone: "08036727833, 0909038904427",
			email: "",
			bio: "Mr. Kenneth Okwudili Omeke is the CEO/MD of Kenomek Int Nig Ltd, a leading dealer in all kinds of welding materials, including iron pipes, iron rods, and general goods. The company operates from No E2 & E3 Maraba Iron Dealers Ass Market, Sharp Corner, behind Chess Pub, along Assembly of God Road. Kenomek Int Nig Ltd is known for providing high-quality welding materials and services to its customers.",
		},
		{
			name: "Amobi Maurice Ali",
			position: "MEMBER",
			imageURL: "assets/img/members/amobi-maurice.jpg",
			phone: "08063511800",
			email: "",
			bio: "Amobi Maurice Ali is a Superintendent of Customs with expertise in International Financial Reporting Standards (IFRSs) and Non-Intrusive Inspection Technology (NIIT). He is based at Office 3, Abidjan Street, Wuse Zone 3, Abuja, and brings extensive knowledge and experience in customs operations and financial reporting.",
		},
		{
			name: "Chief Osita Stephen Alumona",
			position: "MEMBER",
			imageURL: "assets/img/members/osita-alumona.jpg",
			phone: "08036186992, 08058618362",
			email: "ossymillion@gmail.com",
			bio: "Chief Osita Stephen Alumona is the CEO/MD of Ossy Million Global Trust Ltd, a leading name in the building materials industry. With a specialization in high-quality tiles and marble, both foreign and Nigerian, the company is a key distributor for top manufacturers in Nigeria, including Virony Company, Royal Castle Ceramic Company, B.N Ceramics Company, and many more. Ossy Million Global Trust Ltd operates from its head office at Suite A1, Royal Plaza, Dei Dei Junction, Abuja, FCT, with a branch office at Suite B3-214, Dei Dei International Building Materials Market, Abuja, ensuring premium products and exceptional service to its clients.",
		},

		{
			name: "Onyebuchi Wilfred Mamah Ezeh",
			position: "MEMBER",
			imageURL: "assets/img/members/onyebuchi-ezeh.jpg",
			phone: "08037866183",
			email: "",
			bio: "Onyebuchi Wilfred Mamah Ezeh is the MD/CEO of Buchi Furnishing Complex Ltd, a distinguished importer and exporter of high-quality Turkish and Chinese curtains, curtain blinds, bed sheets, cushion cover fabrics, and all forms of interior décor. With a reputation for excellence in service delivery, Buchi Furnishing Complex Ltd also engages in general contracting and merchandise. Strategically located at Black A29, Shop 5, Wuse Market, Abuja, the company ensures top-tier products and outstanding customer satisfaction. Contact us today for premium furnishing solutions—a trial will convince you.",
		},

		{
			name: "Oliver David Onyeke",
			position: "MEMBER",
			imageURL: "assets/img/executive/default-avatar.png",
		},
	],
	resources: [
		{
			icon: "bx bxs-file-doc",
			title: "Our Constitution",
			description:
				"This Document contains our revised constitution dated 25 August 2022",
			downloadlink: "assets/resources/revised-constitution.pdf",
		},
	],
	gallery: [
		{ url: "https://i.ibb.co/BVnVyz8P/gallery-1.jpg" },
		{ url: "https://i.ibb.co/CKjyzJkS/gallery-2.jpg" },
		{ url: "https://i.ibb.co/35X5dGT0/gallery-3.jpg" },
		{ url: "https://i.ibb.co/YFWsnZ5K/gallery-4.jpg" },
		{ url: "https://i.ibb.co/JR2szcx5/gallery-5.jpg" },
		{ url: "https://i.ibb.co/QvbjbbK4/gallery-6.jpg" },
		{ url: "https://i.ibb.co/yc8Rnw2R/gallery-7.jpg" },
		{ url: "https://i.ibb.co/Ndnh1rBp/gallery-8.jpg" },
		{ url: "https://i.ibb.co/0RqK5qzS/gallery-9.jpg" },
		{ url: "https://i.ibb.co/XkjSD7wY/gallery-10.jpg" },
		{ url: "https://i.ibb.co/Kcv4JJpH/gallery-11.jpg" },
		{ url: "https://i.ibb.co/bgG3B6wd/gallery-12.jpg" },
		{ url: "https://i.ibb.co/hxGNjt0T/gallery-13.jpg" },
		{ url: "https://i.ibb.co/BHtXBkxs/gallery-14.jpg" },
		{ url: "https://i.ibb.co/Zp2gJXq4/gallery-15.jpg" },
		{ url: "https://i.ibb.co/Hpz56qQm/gallery-16.jpg" },
		{ url: "https://i.ibb.co/HTLYSHhs/gallery-17.jpg" },
		{ url: "https://i.ibb.co/6RhKCf4c/gallery-18.jpg" },
		{ url: "https://i.ibb.co/21GbrfJG/gallery-19.jpg" },
		{ url: "https://i.ibb.co/Kxhc21jb/gallery-1.jpg" },
		{ url: "https://i.ibb.co/93sZXkq3/gallery-2.jpg" },
		{ url: "https://i.ibb.co/DH6Wp5mS/gallery-3.jpg" },
		{ url: "https://i.ibb.co/nsCfwmxw/gallery-4.jpg" },
		{ url: "https://i.ibb.co/NgDP5J7C/gallery-5.jpg" },
		{ url: "https://i.ibb.co/jkfxSfGY/gallery-6.jpg" },
	],
};
